travis:
  secure:
    BINSTAR_TOKEN: o5AbGUBs23NhbCv5Odf53oaZDZevkx/8jkGmX7HOoBXRfUfQVrQq36QcojYAMsTJulb77xdzpXyyS58rE12NpCogji1BzAns9PBrdd93sO34os1uWo7m5/quupxgpbHNjfzFHtRj89bvCrBOgt2VluX2JYXMaAwF2SqzVsXs13HMg6LVrUpXHQC6jJ8rAkDpjwYjZ81M+NI3Xv9I1ofe1v5pAmzQl4zmGKP+jDmiJp6Q8ssdk9RqTmc6/tIFrzQqVb03rUbKyg/sJmIoBDSpLtxsRpJGVALz1Vf+ZLrV+qX43ueaLH93UR26DXt4TxjB7ddA36lW+kWh8cWR2gCu8iuIHhGeuW4YG/vNVFlzXar1MtX2oRJh2k/+LDd+MCpntEeq0XXrY/l11BdWmVKz4VXUgpGSAIZMg0jGK8my4smUCrn/P2VQEo4SMqw90ZJMqwNbpKLpFKj1y8f8/v2scuwwleBVSBg6rALZ+Pt0iY2UBz2+GdxNyUSEyWMIYW0s1kDOfywdk/liCAqJt3mutT9WZmgpLkphKczgRKdG2puGY/y3Nchl8w7lJK5VuEPuYdobYeo7qSsJq3cLy4jtmGWlAz1c2EQHGQk2uLpaLa3oqlKSFJwK1G2JhCRJdg+AXagiQlFrfEvOfeHSmFqNInGIBohjcqnatFz4D0uUXkk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
