appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: adWHK+A11fbWtuY1vlvti/KsW8HYjY10JCPeyhohF3lqU+obypDVdfaE6MQ0xniiK19Bnaglgaqt8XdwaeMcTPBhCfawbyXfdj8vtr60ogJMHK9w7V0RaoIKnzod/t4LvVkv+Q58FzHw7EVYvRPpP0ckl1VdBA82ECAyoJrSfoWpW1pMQU1TctLmLN2D5mhIU9aoACFYIga4QMGwlZP+VgFJTx4cb5UrlX/ofJyZopmiKqn4tLfphuONEs4H+HeeG49hvwuyZOHkYBTthxW/SIETiTMejKzemaTK/8CJGXnSfAtk6HMThj8Wnj+f+yN16uJQnpsbY9VRgfzNNOjPhQVGInlFKNQ4THk2Rg42mpZV+gjZuKSgB/Ie77WKBqvrcWrAR9XfQEtrLoAcg5XIQHFu4wdF16CpbBwu6fVHzFb6a8KyOM5XRUQwdyEXmStrmd1WcgLY/BeC0cqbO6+FtvKb7ZaswHxAQe8XkAo7+8K3kxGVLgTXmJZzZmn6eA8TW9ICdUJ2/eBzrEdavKiYsITy4aksqm6wAz+CBGhRb4YING5uvS9Vlb0ciaK5FHiFC5tKS2pOFh4T5qIRxedtR8xHjSqx7ikRJEQczfVy8XbttwiFL5hVpYXtnMyuFvAEszzNtK+mGFdLsSLk5v2EUGT2+Vb/KVTYtkakgqGX2wI=}
